# Generated by Django 5.2.4 on 2025-07-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelstats',
            options={'get_latest_by': 'parsed_at', 'ordering': ['-parsed_at'], 'verbose_name': 'Статистика канала', 'verbose_name_plural': 'Статистика каналов'},
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='pinned_messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='last_messages',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Последние сообщения'),
        ),
    ]
