# Generated by Django 5.2.4 on 2025-07-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_channelstats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='parsed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='pinned_messages',
            field=models.TextField(blank=True, null=True, verbose_name='Закрепленное сообщение'),
        ),
    ]
