# Generated by Django 5.2.4 on 2025-07-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_telegramchannel_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='average_views',
            field=models.IntegerField(default=0, verbose_name='Среднее количество просмотров'),
        ),
    ]
