# Generated by Django 5.2.4 on 2025-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_telegramchannel_average_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='pinned_messages',
            field=models.JSONField(blank=True, null=True, verbose_name='Закрепленное сообщение'),
        ),
    ]
