# Generated by Django 5.2.4 on 2025-07-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_alter_telegramchannel_pinned_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='pinned_messages',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Закрепленное сообщение'),
        ),
    ]
